### PR TITLE
Fixed typo error in language_detection_pretext.txt

### PR DESCRIPTION
**Pull request by vivekBoii**
agaisnt -> against

### CODE REVIEW

**Comment by Kav-K** [comment]
Please do all typo changes in one PR and not multiple @vivekBoii

**Comment by vivekBoii** [comment]
ok

**Comment by vivekBoii** [comment]
@Kav-K done all typo error

**Comment by vivekBoii** [comment]
@Kav-K done all typo error

**Comment by Kav-K** [comment]
@vivekBoii please fix the merge conflicts

**Comment by vivekBoii** [comment]
image
somebody had send pull request of typo after me and that,s why merge happened

**Pull request closed without merging**
