### PR TITLE
Add perspectiveapi for moderation

### PR DESCRIPTION
**Pull request by Paillat-dev**

### CODE REVIEW

**Comment by Kav-K** [comment]
Nice! What does aiolimiter do?

**Comment by Paillat-dev** [comment]
Soooo
Here it is:
1. Use /mod perspective_config for setting the tresholds with perspective.
2. Language detection can now be applyed to many languages thanks to perspectiveapi.

The added environement variables are:
- `PERSPECTIVE_API_KEY`: the perspectiveapi api key
- `MODERATION_SERVICE`: choose between `openai` and `perspective`, defaults to `openai`
- `LANGUAGE_DETECT_SERVICE`: overrides the language detection service to be different, defaults to the set `MODERATION_SERVICE`
- `FORCE_LANGUAGE`: can be one of the following: Arabic (ar), Chinese (zh), Czech (cs), Dutch (nl), English (en), French (fr), German (de), Hindi (hi), Hinglish (hi-Latn), Indonesian (id), Italian (it), Japanese (ja), Korean (ko), Polish (pl), Portuguese (pt), Russian (ru), Spanish (es), Swedish (sv).
- `FORCE_ENGLISH`: becomes an alias that sets `FORCE_LANGUAGE="en"` when `FORCE_LANGUAGE` is not set.

Openai language detection works only for english, and if another language is set while openai is the language detection service, lanuage detection will be disabled and a message will be printed in the terminal.

**Comment by Paillat-dev** [comment]
> Nice! What does aiolimiter do?

It allows me to ratelimit the calls of the api to one per second to avoid being rate limited

**Comment by Paillat-dev** [comment]
I will let this draft for some more time so that I can test it more and find any possible bugs.

**Comment by Paillat-dev** [comment]
I think that It could be nice to add some knd of multi-language message replying to the enforce language, when using perspective. So it will warn the user in its language.

**Comment by Kav-K** [comment]
> I think that It could be nice to add some knd of multi-language message replying to the enforce language, when using perspective. So it will warn the user in its language.
> 
> Edit: Just pushed it to the branch

Yeah this would be nice, I guess we can have a layer one level above moderations that just checks what language the message was in and then outputs a locale string, and then that locale string can be passed into some sort of config file that we have locally that contains the translations of the error message in the different locales, keyed by the locale string, no need to have an LLM call for this

**Comment by Kav-K** [comment]
How is this going generally? When would you like me to give it a full review? @Paillat-dev

**Comment by Paillat-dev** [comment]
> How is this going generally? When would you like me to give it a full review? @Paillat-dev 

I am still testing a bit, and I would like that add some more error handling before, I'll let you know.

**Comment by Paillat-dev** [comment]
I'll also write some docs in the AI-MODERATION md

**Comment by Paillat-dev** [comment]
@Kav-K I'm good.

**Comment by Kav-K** [comment]
Sorry for the delays on this, been a bit busy, will take a look ASAP @Paillat-dev

**Comment by Paillat-dev** [comment]
> Sorry for the delays on this, been a bit busy, will take a look ASAP @Paillat-dev

Yup, take the time needed, there is no hurry :)

**Comment by Paillat-dev** [comment]
Heyy, do I keep this open or do I close it?

**Comment by Kav-K** [comment]
@Paillat-dev I've just been busy and sick recently, will review when I can

**Comment by Kav-K** [comment]
@Paillat-dev Before I go ahead and test this thoroughly on my end, did you test this thoroughly locally on your end?

**Comment by Paillat-dev** [comment]
> @Paillat-dev Before I go ahead and test this thoroughly on my end, did you test this thoroughly locally on your end? 

I did test it, and tried to recreate as many situations as I could.

**Comment by Kav-K** [comment]
Sounds good thanks, will test asap

**Comment by Paillat-dev** [comment]
Just rebased with your main but no real change

**Comment by Paillat-dev** [comment]
@Kav-K Do I keep this open?

**Comment by Paillat-dev** [comment]
Ok Imma close this.

**Pull request closed without merging**
