### PR TITLE
fix(/gpt converse command): handle cases where ctx.respond() fails by…

### PR DESCRIPTION
**Pull request by Paillat-dev**
… falling back to ctx.message.reply() or ctx.send()
see #368

### CODE REVIEW

**Comment by Kav-K** [comment]
This looks good to me on glance, I'm not on my computer, but have you tested this out locally? e.g sending it a message and deleting it and seeing what happens? can you also extend it to work for internet chat and code chat and index chat?

**Comment by Paillat-dev** [comment]
> This looks good to me on glance, I'm not on my computer, but have you tested this out locally? e.g sending it a message and deleting it and seeing what happens? can you also extend it to work for internet chat and code chat and index chat?

Yes I've tested it deleting a message. I'll see what I can do for the other chats.

**Comment by Paillat-dev** [comment]
Added more commits, but I couldn't test all of the chats since I did not have all of the required apis and services set up. I would appreciate if you could test it for me.

**Comment by Kav-K** [comment]
I think there are some other cases where this error might be thrown, like when the agent responds to a message in the conversation after these sets of initial messages are sent, also, can you make these more abstracted? Some sort of try_ctx_respond() method that does the functionality so we don't have code duplication like this?

**Comment by Paillat-dev** [comment]
> I think there are some other cases where this error might be thrown, like when the agent responds to a message in the conversation after these sets of initial messages are sent, also, can you make these more abstracted? Some sort of try_ctx_respond() method that does the functionality so we don't have code duplication like this?

I will abstract the function to a utilitary, and will place it to all of the .respond that migth be concerned. Where would you prefer that function to be located? I don't see any utils folder that's why I ask.

Also, do you have a traceback of one of the Unknown Interaction errors? It migth help as well.

**Comment by Paillat-dev** [comment]
Closed, I will repoen from a different branch

**Pull request closed without merging**
